# Enabled
ENCODER_MAP_ENABLE = yes
VIA_ENABLE = yes
MAGIC_ENABLE = yes
LTO_ENABLE = yes

# Disabled
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
MUSIC_ENABLE = no
GRAVE_ESC_ENABLE = no
SPACE_CADET_ENABLE = no